Nazwa = input ('Napisz swoją nazwę: ')
Hasło = input ('Napisz hasło do swojego konta: ')
Adres = input ('Napisz swój adres zamieszkania: ')
Email = input ('Napisz swój adres E-Mail: ')
Numer = input ('Napisz swój nr Telefonu: ')
print ('---------------------------------------------------------------------')
print ('Twoja nazwa użytkownika to: ' + Nazwa)
print (' ')
print ('Hasło do twojego konto to: ' + Hasło)
print (' ')
print ('Twój adres zamieszkania to: ' + Adres)
print (' ')
print ('Twój adres E-Mail to: ' + Email)
print (' ')
print ('Twój nr telefonu to: ' + Numer)
